package com.moqim.list.feature.plans.model

import com.moqim.list.feature.home.model.DailyPlanEditorUiModel
import com.moqim.list.feature.home.model.TaskItemUiModel

data class PlansUiState(
    val title: String = "计划中心",
    val description: String = "按月、周、日统一编排目标、任务池与时段执行。",
    val currentLayer: PlanningLayer = PlanningLayer.DAY,
    val selectedDate: String = "",
    val dateChips: List<PlanningDateChipUiModel> = emptyList(),
    val monthlyPlans: List<MonthlyPlanItemUiModel> = emptyList(),
    val weeklyPlans: List<WeeklyPlanItemUiModel> = emptyList(),
    val weeklyProgress: List<WeeklyPlanProgressUiModel> = emptyList(),
    val inboxTasks: List<PlanningTaskUiModel> = emptyList(),
    val weekPoolTasks: List<PlanningTaskUiModel> = emptyList(),
    val weekPoolHint: String = "",
    val daySegments: List<PlanningSegmentUiModel> = emptyList(),
    val completedDayTasks: List<PlanningTaskUiModel> = emptyList(),
    val dayTemporaryTasks: List<PlanningTaskUiModel> = emptyList(),
    val temporaryLists: List<TemporaryListUiModel> = emptyList(),
    val selectedTemporaryListKey: String = "inbox",
    val selectedDailyPlanId: Long? = null,
    val selectedDailyPlanWeeklyPlanId: Long? = null,
    val selectedDailyPlanWeeklyPlanTitle: String = "",
    val selectedDailyPlanSummary: String = "",
    val selectedDailyPlanEnergy: String = "MEDIUM",
    val selectedDailyPlanReview: String = "",
    val selectedDayWeekPoolBridgeText: String = "",
    val selectedDaySuggestionItems: List<String> = emptyList(),
    val selectedDayTopFocusTitles: List<String> = emptyList(),
    val selectedDayLoadSummary: String = "",
    val selectedDayCapacitySummary: String = "",
    val selectedDayCompletedCount: Int = 0,
    val selectedDayTemporaryCount: Int = 0,
    val selectedDayHabitProgressText: String = "",
    val feedbackMessage: String? = null,
    val selectedMonthlyPlan: MonthlyPlanItemUiModel? = null,
    val selectedWeeklyPlan: WeeklyPlanItemUiModel? = null,
    val editingMonthlyPlan: MonthlyPlanItemUiModel? = null,
    val editingWeeklyPlan: WeeklyPlanItemUiModel? = null,
    val creatingMonthlyPlan: MonthlyPlanItemUiModel? = null,
    val creatingWeeklyPlan: WeeklyPlanItemUiModel? = null,
    val editingDailyPlan: DailyPlanEditorUiModel? = null,
    val editingTask: TaskItemUiModel? = null,
    val creatingTask: TaskItemUiModel? = null,
    // AI 导入相关
    val showingTextImportDialog: Boolean = false,
    val showingImportPreview: Boolean = false,
    val importPreviewText: String = "",
    val importInputText: String = "",
)
